training:
  seed: 0
  resume_from_checkpoint: null  # null to start from scratch
  inference_mode: mean  # mean, all, random_search, gradient_ascent
  inference_kwargs:
    num_steps: 1
    lr: 5e-2
  batch_size: 128  # this has to be divisible by gradient_accumulation_steps * num_devices
  gradient_accumulation_steps: 4  # the higher the slower but the lower memory usage while keeping effective batch size constant
  total_num_steps: 500000
  log_every_n_steps: 10  # this has to respect dataset_size >= batch_size * log_every_n_steps
  eval_every_n_logs: 1000  # null to disable eval
  save_checkpoint_every_n_logs: 1000  # null to disable checkpointing
  learning_rate: 4e-4
  prior_kl_coeff: null
  pairwise_kl_coeff: null
  mixed_precision: True  # if True, it uses bfloat16 for activations (params stay in float32)
  online_data_augmentation: True
  task_generator:
    num_workers: 200
    num_pairs: 4
    class: V4
  train_datasets:


eval:
  eval_datasets:
  test_datasets:
    - generator: V4
      task_generator_kwargs:
        timeout_generate_task: 0
      name: generator_mean
      num_pairs: 4
      length: 48
      batch_size: 16
      num_tasks_to_show: 48
    - generator: V4
      task_generator_kwargs:
        timeout_generate_task: 0
      name: generator_gradient_ascent_1
      num_pairs: 4
      length: 48
      batch_size: 16
      num_tasks_to_show: 48
      inference_mode: gradient_ascent
      inference_kwargs:
        num_steps: 1
        lr: 5e-2
    - generator: V4
      task_generator_kwargs:
        timeout_generate_task: 0
      name: generator_gradient_ascent_20
      num_pairs: 4
      length: 48
      batch_size: 16
      num_tasks_to_show: 48
      inference_mode: gradient_ascent
      inference_kwargs:
        num_steps: 20
        lr: 5e-2
    - folder: storage/arc_train_438_3
      use_hf: True
      length: 32
      batch_size: 16
      num_tasks_to_show: 32
  json_datasets:
    - challenges: json/arc-agi_training_challenges.json
      solutions: json/arc-agi_training_solutions.json
      name: mean
      only_n_tasks: 100
      num_tasks_to_show: 50
    - challenges: json/arc-agi_training_challenges.json
      solutions: json/arc-agi_training_solutions.json
      name: gradient_ascent_20
      only_n_tasks: 100
      num_tasks_to_show: 50
      inference_mode: gradient_ascent
      inference_kwargs:
        num_steps: 20
        lr: 5e-2
    - challenges: json/arc-agi_evaluation_challenges.json
      solutions: json/arc-agi_evaluation_solutions.json
      name: mean
      only_n_tasks: 100
      num_tasks_to_show: 50
    - challenges: json/arc-agi_evaluation_challenges.json
      solutions: json/arc-agi_evaluation_solutions.json
      name: gradient_ascent_20
      only_n_tasks: 100
      num_tasks_to_show: 50
      inference_mode: gradient_ascent
      inference_kwargs:
        num_steps: 20
        lr: 5e-2


encoder_transformer:
  _target_: src.models.utils.EncoderTransformerConfig
  max_rows: 30
  max_cols: 30
  num_layers: 4
  transformer_layer:
    _target_: src.models.utils.TransformerLayerConfig
    num_heads: 8
    emb_dim_per_head: 32
    mlp_dim_factor: 4.0
    dropout_rate: 0.0
    attention_dropout_rate: 0.0
  latent_dim: 128
  variational: False
  latent_projection_bias: False


decoder_transformer:
  _target_: src.models.utils.DecoderTransformerConfig
  max_rows: 30
  max_cols: 30
  num_layers: 8
  transformer_layer:
    _target_: src.models.utils.TransformerLayerConfig
    num_heads: 8
    emb_dim_per_head: 64
    mlp_dim_factor: 4.0
    dropout_rate: 0.0
    attention_dropout_rate: 0.0
